name: Deploy to GitHub Pages
on:
  push:
    branches: [master scott/gihtub_action_test]
  workflow_dispatch:
env:
  OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-ghp@master
#         with: {pre: 1}